source 'https://rubygems.org'

gem 'rack'
gem 'grape', '0.11.0'
gem 'grape-entity', '0.4.5'
gem 'oj'
gem 'nokogiri', '~> 1.8'
gem 'rack-cors', '0.3.1'
gem 'mime-types', '2.4.3'
gem 'activemodel', '~> 4.2'
